name: Deploy Kubernetes on AWS

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Save master IP
        id: masterip
        working-directory: terraform
        run: echo "MASTER_IP=$(terraform output -raw master_public_ip)" >> $GITHUB_ENV

  k8s:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Install SSH & Kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y ssh
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy kubeconfig
        run: |
          scp -o StrictHostKeyChecking=no ubuntu@${MASTER_IP}:/home/ubuntu/.kube/config ./kubeconfig
          mkdir -p ~/.kube
          cp ./kubeconfig ~/.kube/config

      - name: Verify Cluster
        run: kubectl get nodes -o wide

      - name: Deploy Ingress Controller
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

      - name: Deploy Juice Shop
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/juice-shop-deployment.yaml
          kubectl apply -f k8s/juice-shop-service.yaml
          kubectl apply -f k8s/juice-shop-ingress.yaml
