name: Terraform AWS K8s Cluster & Deploy Juice Shop

on:
  workflow_dispatch:

env:
  TF_WORKING_DIR: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      master_ip: ${{ steps.tfoutputs.outputs.master_ip }}
      worker_ips: ${{ steps.tfoutputs.outputs.worker_ips }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_ssh_public_key: ${{ secrets.K8S_SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve

      - name: Save Outputs
        id: tfoutputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          # Master IP
          MASTER_IP=$(terraform output -raw master_public_ip)
          echo "master_ip=$MASTER_IP" >> $GITHUB_OUTPUT

          # Worker IPs: convert JSON array to space-separated string
          WORKER_IPS=$(terraform output -json worker_public_ips | jq -r '.[]')
          echo "worker_ips=$WORKER_IPS" >> $GITHUB_OUTPUT

      - name: Get Join Command from Master
        id: get_join_cmd
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ steps.tfoutputs.outputs.master_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cat /home/ubuntu/join-command.txt

      - name: Join Workers to Cluster
        run: |
          for IP in ${{ steps.tfoutputs.outputs.worker_ips }}; do
            echo "Joining worker $IP to cluster"
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$IP "sudo ${{ steps.get_join_cmd.outputs.stdout }}"
          done

      - name: Deploy Juice Shop & Ingress
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ steps.tfoutputs.outputs.master_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            kubectl apply -f ~/juice-shop-deployment.yaml
            kubectl apply -f ~/juice-shop-service.yaml
            kubectl apply -f ~/juice-shop-ingress.yaml
