name: Terraform AWS K8s Cluster & Deploy Juice Shop

on:
  workflow_dispatch:

env:
  TF_WORKING_DIR: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Get Master IP
        id: get_ip
        run: |
          MASTER_IP=$(terraform output -state=${{ env.TF_WORKING_DIR }}/terraform.tfstate master_public_ip)
          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Deploy Juice Shop & Ingress
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.MASTER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            kubectl apply -f ~/juice-shop-deployment.yaml
            kubectl apply -f ~/juice-shop-service.yaml
            kubectl apply -f ~/juice-shop-ingress.yaml
